### ISSUE TITLE
submitting throws exception when pending attrebute is not set

### ISSUE THREAD

**Issue by omerax** [bendrucker/angular-form-state#3]
I use the `submit-button` directive in order to get the button disabled. I use my own animation for the button submit state, and don't set the 'pending' attrebute.

when the form state is changed to pending, the function $interpulate :
`element.text($interpolate(pending ? attributes.pending : original)(scope));`
throws TypeError: Cannot read property 'length' of undefined
since `attributes.pending` is undefined.
maybe add a check whether it is set ? like this:
`element.text($interpolate(pending &&  attributes.pending  ? attributes.pending : original)(scope));`

thanks!

**Comment by bendrucker** [comment]
Done!

**Comment by altryne** [comment]
Wohoo! Thanx @bendrucker

**Comment by omerax** [comment]
thx :+1:
