### ISSUE TITLE
Module 'angular-form-state' is not available! 

### ISSUE THREAD

**Issue by LunarDevelopment** [bendrucker/angular-form-state#4]
Ola! 

I'm having some difficulty getting this plugin working? 

When I include the  'angular-form-state' in my app init I get the title error message,while if I include 'bd.form-state' which looks like release/angular-form-state.js is exporting as, my app initializes fine. 

Is the README.MD wrong or am I only pulling part of the library into my app..? 

Lewis

**Comment by bendrucker** [comment]
Sorry for the delay, readme was indeed wrong on the angular module name
