### ISSUE TITLE
model binding is not working on submit-button

### ISSUE THREAD

**Issue by MaaikeB** [bendrucker/angular-form-state#5]
I have a submit button with text that is bind to my model:
`<button submit-button>{{ MyCtrl.myChangingText }}</button>`

Even before the button is clicked (and the state changes to pending), the text doesn't change with the model. 

It seems this is due to line 97 of the release file:
`element.text($interpolate(pending && pendingText != null ? pendingText : original)(scope))`

Might the solution be to invoke the $interpolate only if pending is true?
` if (pending && pendingText != null) { element.text($interpolate(pendingText)(scope)) }`

**Comment by bendrucker** [comment]
Can you submit a failing test via PR?

**Comment by bendrucker** [comment]
Think I managed to figure it out -- let me know!

**Comment by MaaikeB** [comment]
:+1: works like charm. thanks!
